### ISSUE TITLE
Displaying data/spreadsheet on GitHub

### ISSUE THREAD

**Issue by victorchks** [BIOL548O/Discussion#13]
Hey @aammd ,

I've pushed my R file up to GitHub (Data Sorting.R) with a small bit of code to rename the columns. However, I can't seem to see the spreadsheet displayed on my browser. Could you please advise on how to fix this? Am I supposed to use .R or .MD files for my codes? 

On a side note, when is the spreadsheet due, and are there classes during the reading break?

Thanks!

Vic

**Comment by aammd** [comment]
@victorchks ,  

I just read the code you pushed. You'll need to write your data to a file, and then it will be visible on github. Best practice is to write it into a directory called `data/`, which is alongside `data-raw/`. 

R code should always be kept in a `.R` file. That way, github and Rstudio will know to treat it like R code, and highlight it appropriately.

Homework is due **23rd Feb** at **noon**.

No classes during Reading Week

**Comment by victorchks** [comment]
Thanks @aammd ! I got it to work and have successfully created a CSV file with my columns sorted.
