### ISSUE TITLE
Creating metadata files

### ISSUE THREAD

**Issue by victorchks** [BIOL548O/Discussion#23]
Hey @aammd ,

@yfangzoology and I couldn't really catch up with Thursday's class about metadata, so we have a question about the assignment. From what I recall, creating a YAML file was simply just using `write.csv`, renaming the output CSV file to a .csvy file, and then adding in the lines that's shown on the course page to create the metadata.

However, looking at the course instructions for YAML and CSVY, it says we also need to use the `rio` package to create the metadata, but I don't remember if we ever went through that process during class.

Do we need to use `rio`, or can we simply use the former method I mentioned? If it's not critical for us to have the metadata script done by Tuesday, would you be able to go through it again during class?

Thanks!

Vic

**Comment by aammd** [comment]
no NO i just saw this! :flushed: @victorchks and @yfangzoology was our recap in class today helpful to you? I hope so!

**Comment by victorchks** [comment]
Thanks @aammd ! I think the recap class went over it well enough; I think it was just self-doubt that we had because of how easy it was to create a CSVY compared to the other formats.
