### ISSUE TITLE
Finding data for mairindeith

### ISSUE THREAD

**Issue by aammd** [BIOL548O/Discussion#5]
Hello @mairindeith,

In the pre-course survey, you indicated that you don't have any data. Experience with real data is more useful to you than working through exercises with your own messy data. Therefore, I wanted to have a discussion with you about what kind of data you might be able to use.  

Here are some suggestions (ranked _very_ loosely from most to least helpful):  
- [ ] Data from a pilot experiment  
- [ ] Data from your supervisor / collaborator / senior grad student   (assure them that these data will remain confidential and unpublished)
- [x] Data from any previous degree you've done (Honours / Masters). This would be especially useful to you if the data are unpublished (even if the paper _is_ published)
- [ ] Published data from a paper in your field
- [ ] Data emailed to you from an author in your field
- [ ] Data (relevant to your work) obtained from the Web -- ie from a data archive or elsewhere. If you know where to look, i can help you get it.
## Plan B

If none of the above datasets work, we'll have to find something else. This could be a part of the Kaggle dataset, the candy dataset, or some other random dataset you enjoy. I could also give you some of my own data which are still unpublished.

Which of these options appeals most to you? Let's try to figure this out by Thursday.  

Andrew

**Comment by mairindeith** [comment]
Hi Andrew, 

I have a large data set from an undergraduate honours degree that I can use. The dataset hasn't been published as of yet. It is similar enough data to what I'll be using for my masters (population and environmental data), so I think it can work for now at least. 

Thanks for checking in, and please let me know if you don't think this will work. 

Mairin

_P.s. Nice Markdown formatting_

**Comment by aammd** [comment]
@mairindeith  that sounds awesome. I'm going to suggest to everyone that we start with the most raw, untouched form of the data that we can find. (as long as its practical. eg not hundreds of hours of camera trap data :movie_camera: )

So to that end, when you say "population data", what is that exactly? samples with counts of species, or mark-recapture data, etc

Andrew

PS oh why thank you! :blush: :flushed:

**Comment by mairindeith** [comment]
The data is simple census data - species counts at a bunch of different sites for Pacific coral reef fish. 

Mairin

**Comment by aammd** [comment]
:fish: :fish: :fish: :fish: :fish: 
:tropical_fish: :tropical_fish: 
:whale2: 

Sounds perfect!
