### ISSUE TITLE
Finding data for scienceisfiction

### ISSUE THREAD

**Issue by aammd** [BIOL548O/Discussion#7]
Hello @scienceisfiction,

In the pre-course survey, you indicated that you don't have any data. Experience with real data is more useful to you than working through exercises with your own messy data. Therefore, I wanted to have a discussion with you about what kind of data you might be able to use.  

Here are some suggestions (ranked _very_ loosely from most to least helpful):  
- [ ] Data from a pilot experiment  
- [ ] Data from your supervisor / collaborator / senior grad student   (assure them that these data will remain confidential and unpublished)
- [ ] Data from any previous degree you've done (Honours / Masters). This would be especially useful to you if the data are unpublished (even if the paper _is_ published)
- [ ] Published data from a paper in your field
- [ ] Data emailed to you from an author in your field
- [ ] Data (relevant to your work) obtained from the Web -- ie from a data archive or elsewhere. If you know where to look, i can help you get it.
## Plan B

If none of the above datasets work, we'll have to find something else. This could be a part of the Kaggle dataset, the candy dataset, or some other random dataset you enjoy. I could also give you some of my own data which are still unpublished.

Which of these options appeals most to you? Let's try to figure this out by Thursday.  

Andrew

**Comment by aammd** [comment]
Hey there @scienceisfiction . Just confirming what we were discussing yesterday -- you'll be working with some data that you have from your supervisor. It sounds like it will provide a really useful challenge!

**Comment by scienceisfiction** [comment]
Yes! Let me double check with Doug to make sure he's OK with that but otherwise that's the plan.
