### ISSUE TITLE
Finding data for jotheria

### ISSUE THREAD

**Issue by aammd** [BIOL548O/Discussion#8]
Hello @jotheria,

In the pre-course survey, you indicated that you don't have any data. Experience with real data is more useful to you than working through exercises with your own messy data. Therefore, I wanted to have a discussion with you about what kind of data you might be able to use.  

Here are some suggestions (ranked _very_ loosely from most to least helpful):  
- [ ] Data from a pilot experiment  
- [ ] Data from your supervisor / collaborator / senior grad student   (assure them that these data will remain confidential and unpublished)
- [ ] Data from any previous degree you've done (Honours / Masters). This would be especially useful to you if the data are unpublished (even if the paper _is_ published)
- [ ] Published data from a paper in your field
- [ ] Data emailed to you from an author in your field
- [ ] Data (relevant to your work) obtained from the Web -- ie from a data archive or elsewhere. If you know where to look, i can help you get it.
## Plan B

If none of the above datasets work, we'll have to find something else. This could be a part of the Kaggle dataset, the candy dataset, or some other random dataset you enjoy. I could also give you some of my own data which are still unpublished.

Which of these options appeals most to you? Let's try to figure this out by Thursday.  

Andrew

**Comment by aammd** [comment]
Just writing down & confirming what we were talking about yesterday -- you'll be working with some undergrad data?

**Comment by jotheria** [comment]
yes, that is correct.

On 10/02/2016 9:25 AM, Andrew MacDonald wrote:

> Just writing down & confirming what we were talking about yesterday -- 
> you'll be working with some undergrad data?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/BIOL548O/Discussion/issues/8#issuecomment-182491204.

## 

Jolan Thériault
MSc. Student
Department of Zoology
University of British Colombia
Vancouver, BC, Canada
jtheriau@zoology.ubc.ca

**Comment by aammd** [comment]
Excellent! :sunglasses:
